name: mynodeflow
'on':
  issue_comment:
    types:
      - created
      - edited
  issues:
    types: opened
jobs:
  myjob:
    runs-on: ubuntu-latest
    steps:
      - name: Use Issue Management Action
        uses: sammychinedu2ky/issue-man@main
        with:
          myToken: '${{ secrets.GITHUB_TOKEN }}'
          key: '${{secrets.KEY}}'
          endpoint: '${{secrets.ENDPOINT}}'
